apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "azure-pricing-rest-dynamic-controller-plugin.fullname" . }}
  labels:
  {{- include "azure-pricing-rest-dynamic-controller-plugin.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }} 
  PLUGIN_PORT: "{{ .Values.service.port }}"
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "azure-pricing-rest-dynamic-controller-plugin.fullname" . }}-openapi
  labels:
  {{- include "azure-pricing-rest-dynamic-controller-plugin.labels" . | nindent 4 }}
data:
  schema.yaml: |
    components:
      schemas:
        resource.Quantity:
          properties:
            Format:
              enum:
              - DecimalExponent
              - BinarySI
              - DecimalSI
              type: string
              x-enum-comments:
                BinarySI: e.g., 12Mi (12 * 2^20)
                DecimalExponent: e.g., 12e6
                DecimalSI: e.g., 12M  (12 * 10^6)
              x-enum-varnames:
              - DecimalExponent
              - BinarySI
              - DecimalSI
          type: object
        retail.Price:
          properties:
            armRegionName:
              type: string
            armSkuName:
              type: string
            currencyCode:
              type: string
            effectiveStartDate:
              type: string
            isPrimaryMeterRegion:
              type: boolean
            location:
              type: string
            meterId:
              type: string
            meterName:
              type: string
            productId:
              type: string
            productName:
              type: string
            retailPrice:
              $ref: '#/components/schemas/resource.Quantity'
            serviceFamily:
              type: string
            serviceId:
              type: string
            serviceName:
              type: string
            skuId:
              type: string
            skuName:
              type: string
            tierMinimumUnits:
              $ref: '#/components/schemas/resource.Quantity'
            type:
              type: string
            unitOfMeasure:
              type: string
            unitPrice:
              $ref: '#/components/schemas/resource.Quantity'
          type: object
    externalDocs:
      description: OpenAPI
      url: https://swagger.io/resources/open-api/
    info:
      contact:
        email: contact@krateoplatformops.io
        name: Krateo Support
        url: https://krateo.io
      description: Simple wrapper around Azure Pricing API for Krateo Operator Generator
        (KOG)
      license:
        name: Apache 2.0
        url: http://www.apache.org/licenses/LICENSE-2.0.html
      termsOfService: http://swagger.io/terms/
      title: Azure Pricing Plugin API for Krateo Operator Generator (KOG)
      version: "1.0"
    openapi: 3.1.0
    paths:
      /api/retail/prices:
        get:
          description: Get all Azure retail prices
          operationId: get-prices
          parameters:
          - description: filter for the retail prices
            in: query
            name: $filter
            required: true
            schema:
              type: string
          responses:
            "200":
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/retail.Price'
              description: OK
          summary: Get all Azure retail prices
    servers:
    - url: http://{{ .Values.env.HOST_PLUGIN }}.{{ .Release.Namespace }}:{{ .Values.service.port }}/api/retail
